version: '3.8'

services:
  app:
    image: node:14.16-alpine
    working_dir: $PWD
    env_file: .env
    command: yarn start:dev
    ports:
      - 3000:3000
    volumes:
      - $PWD:$PWD
    depends_on:
      - db

  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
